import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Car rental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-screen scroll-smooth`}
      >
        <div className="min-h-screen flex flex-col">
          <div className="w-full px-4 sm:px-6 md:px-12 lg:px-24 xl:px-48 2xl:px-80">
            <Navbar />
          </div>
          <main className="flex-1 w-full px-4 sm:px-6 md:px-12 lg:px-24 xl:px-48 2xl:px-80">
            {children}
          </main>
          <div className="w-full px-4 sm:px-6 md:px-12 lg:px-24 xl:px-48 2xl:px-80">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
